package com.example.robotic_events_test;

import android.util.Log;

import com.google.android.gms.tasks.Task;
import com.google.firebase.firestore.CollectionReference;
import com.google.firebase.firestore.DocumentSnapshot;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.firestore.QuerySnapshot;
import com.google.firebase.firestore.SetOptions;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

public class EventModel {
    private final FirebaseFirestore db;
    private final CollectionReference eventsCollection;

    EventModel(String collectionName) {
        this.db = FirebaseFirestore.getInstance();
        this.eventsCollection = db.collection(collectionName);

        // EventModel eventModel = new EventModel("events_mock");
    }

    EventModel() {
        this("events");
    }

    public void saveEvent(
            String id,
            String title,
            String description,
            long dateTime,
            String location,
            int totalCapacity,
            double price,
            String organizerId,
            String category,
            String imageUrl
    ) {
        Map<String, Object> eventData = new HashMap<>();
        eventData.put("title", title);
        eventData.put("description", description);
        eventData.put("dateTime", dateTime);
        eventData.put("location", location);
        eventData.put("category", category);
        eventData.put("organizerId", organizerId);
        eventData.put("totalCapacity", totalCapacity);
        eventData.put("status", "open");
        eventData.put("price", price);
        eventData.put("imageUrl", imageUrl);
        eventData.put("waitlist", new ArrayList<>());

        if (id != null && !id.isEmpty()) {
            eventData.put("id", id);
            // .set() will overwrite the entire document (if it exists)
            eventsCollection.document(id)
                    .set(eventData)
                    .addOnSuccessListener(aVoid ->
                            Log.d("EventModel", "Event saved with ID " + id))
                    .addOnFailureListener(e ->
                            Log.e("EventModel", "Error saving event", e));
        } else {
            eventsCollection.add(eventData)
                    .addOnSuccessListener(documentRef -> {
                        String generatedId = documentRef.getId();
                        documentRef.update("id", generatedId);
                        Log.d("EventModel", "Event added with autogenerated ID " + generatedId);
                    })
                    .addOnFailureListener(e ->
                            Log.e("EventModel", "Error adding event", e));
        }
    }

    public Task<DocumentSnapshot> getEvent(String id) {
        return eventsCollection.document(id).get();
    }

    public Task<QuerySnapshot> getAllEvents() {
        return eventsCollection.get();
    }

    public Task<Void> updateEvent(String id, Map<String, Object> data) {
        if (id == null || id.isEmpty()) {
            throw new IllegalArgumentException("Document ID cannot be null or empty");
        }
        return eventsCollection.document(id).update(data);
    }

    public Task<Void> deleteEvent(String id) {
        if (id == null || id.isEmpty()) {
            throw new IllegalArgumentException("Document ID cannot be null or empty");
        }
        return eventsCollection.document(id).delete();
    }
}