package com.example.robotic_events_test;

import android.util.Log;
import com.google.android.gms.tasks.Task;
import com.google.firebase.firestore.CollectionReference;
import com.google.firebase.firestore.DocumentSnapshot;
import com.google.firebase.firestore.EventListener;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.firestore.ListenerRegistration;
import com.google.firebase.firestore.QuerySnapshot;
import java.util.ArrayList;
import java.util.List;


/**
 * MODEL: Event model
 * performs operations on the db relating to events
 */
public class EventModel {
    private final CollectionReference eventsCollection;

    EventModel(String collectionName) {
        FirebaseFirestore db = FirebaseFirestore.getInstance();
        this.eventsCollection = db.collection(collectionName);
    }

    EventModel() {
        this("events");
    }


    /**
     * Saves an event to the Firestore database.
     * If the event already has an ID, it will be updated. Otherwise, a new document will be created.
     *
     * @param event The event to save.
     */
    public void saveEvent(Event event) {
        String id = event.getId();

        if (id != null && !id.isEmpty()) {
            // .set() will overwrite the entire document
            eventsCollection.document(id)
                    .set(event)
                    .addOnSuccessListener(aVoid ->
                            Log.d("EventModel", "Event saved with ID " + id))
                    .addOnFailureListener(e ->
                            Log.e("EventModel", "Error saving event", e));
        } else {
            eventsCollection.add(event)
                    .addOnSuccessListener(documentRef -> {
                        String generatedId = documentRef.getId();
                        documentRef.update("id", generatedId);
                        Log.d("EventModel", "Event added with autogenerated ID " + generatedId);
                    })
                    .addOnFailureListener(e ->
                            Log.e("EventModel", "Error adding event", e));
        }
    }

    /**
     * Retrieves an event from the Firestore database by its ID.
     *
     * @param id The ID of the event to retrieve.
     */

    public Task<Event> getEvent(String id) {
        return eventsCollection.document(id).get().continueWith(task -> {
            DocumentSnapshot document = task.getResult();
            if (document.exists()) {
                return document.toObject(Event.class);
            }
            return null;
        });
    }

    /**
     * Retrieves all events from the Firestore database.
     *
     * @return A Task that will be completed with a list of all events.
     */

    public Task<List<Event>> getAllEvents() {
        return eventsCollection.get().continueWith(task -> {
            if (task.isSuccessful()) {
                return task.getResult().toObjects(Event.class);
            }
            return new ArrayList<>();
        });
    }

    /**
     * Retrieves events from the Firestore database for a specific organizer.
     *
     * @param organizerId The ID of the organizer to filter events by.
     * @return A Task that will be completed with a list of events for the specified organizer.
     */

    // ADDED: Get events only for a specific organizer
    public Task<List<Event>> getOrganizerEvents(String organizerId) {
        return eventsCollection.whereEqualTo("organizerId", organizerId).get().continueWith(task -> {
            if (task.isSuccessful()) {
                return task.getResult().toObjects(Event.class);
            }
            return new ArrayList<>();
        });
    }
    
    public ListenerRegistration addEventsListener(EventListener<QuerySnapshot> listener) {
        return eventsCollection.addSnapshotListener(listener);
    }

    // ADDED: Real-time listener filtered by organizer
    public ListenerRegistration addOrganizerEventsListener(String organizerId, EventListener<QuerySnapshot> listener) {
        return eventsCollection.whereEqualTo("organizerId", organizerId).addSnapshotListener(listener);
    }

    /**
     * Deletes an event from the Firestore database by its ID.
     *
     * @param id The ID of the event to delete.
     */

    public Task<Void> deleteEvent(String id) {
        if (id == null || id.isEmpty()) {
            throw new IllegalArgumentException("Document ID cannot be null or empty");
        }
        return eventsCollection.document(id).delete();
    }
}