package com.example.robotic_events_test;

import android.util.Log;
import com.google.android.gms.tasks.Task;
import com.google.firebase.firestore.CollectionReference;
import com.google.firebase.firestore.DocumentSnapshot;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.firestore.QuerySnapshot;
import java.util.ArrayList;
import java.util.List;

public class EventModel {
    private final FirebaseFirestore db;
    private final String collectionName;
    private final CollectionReference eventsCollection;

    EventModel(String collectionName) {
        this.collectionName = collectionName;
        this.db = FirebaseFirestore.getInstance();
        this.eventsCollection = db.collection(collectionName);
    }

    EventModel() {
        this("events");
    }

    public void saveEvent(Event event) {
        String id = event.getId();

        if (id != null && !id.isEmpty()) {
            // .set() will overwrite the entire document
            eventsCollection.document(id)
                    .set(event)
                    .addOnSuccessListener(aVoid ->
                            Log.d("EventModel", "Event saved with ID " + id))
                    .addOnFailureListener(e ->
                            Log.e("EventModel", "Error saving event", e));
        } else {
            eventsCollection.add(event)
                    .addOnSuccessListener(documentRef -> {
                        String generatedId = documentRef.getId();
                        documentRef.update("id", generatedId);
                        Log.d("EventModel", "Event added with autogenerated ID " + generatedId);
                    })
                    .addOnFailureListener(e ->
                            Log.e("EventModel", "Error adding event", e));
        }
    }

    public Task<Event> getEvent(String id) {
        return eventsCollection.document(id).get().continueWith(task -> {
            DocumentSnapshot document = task.getResult();
            if (document.exists()) {
                return document.toObject(Event.class);
            }
            return null;
        });
    }

    public Task<List<Event>> getAllEvents() {
        return eventsCollection.get().continueWith(task -> {
            if (task.isSuccessful()) {
                return task.getResult().toObjects(Event.class);
            }
            return new ArrayList<>();
        });
    }

    public Task<Void> deleteEvent(String id) {
        if (id == null || id.isEmpty()) {
            throw new IllegalArgumentException("Document ID cannot be null or empty");
        }
        return eventsCollection.document(id).delete();
    }
}